const K="the-vault-cards-v2",K1="the-vault-cards-v1";
const $=id=>document.getElementById(id), $$=q=>[...document.querySelectorAll(q)];
const euro=new Intl.NumberFormat("nl-NL",{style:"currency",currency:"EUR"});
const test=new Set(["one piece tcg|monkey.d.luffy|op05|op05-060","magic: the gathering|sol ring|commander masters|392","one piece tcg|roronoa zoro|op01|op01-025"]);
const norm=c=>({id:c.id||crypto.randomUUID(),game:c.game||"One Piece TCG",name:c.name||"Onbekende kaart",setName:c.setName||"Onbekende set",cardNumber:c.cardNumber||"",rarity:c.rarity||"Rare",condition:c.condition||"Near Mint",quantity:+c.quantity||1,price:+c.price||0,foil:!!c.foil,image:c.image||"",addedAt:+c.addedAt||Date.now()});
const isTest=c=>test.has([c.game,c.name,c.setName,c.cardNumber].join("|").toLowerCase());
function load(){let raw=localStorage.getItem(K)||localStorage.getItem(K1), a=raw?JSON.parse(raw).map(norm).filter(c=>!isTest(c)):[];localStorage.setItem(K,JSON.stringify(a));localStorage.removeItem(K1);return a}
let cards=load(),scanFile=null;
const save=()=>localStorage.setItem(K,JSON.stringify(cards));
const esc=s=>String(s||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const ini=s=>(s||"TCG").split(/[.\s-]+/).filter(Boolean).slice(0,3).map(x=>x[0]).join("").toUpperCase();
function toast(t){let e=$("toast");e.textContent=t;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),1800)}
function nav(p){$$('.page').forEach(x=>x.classList.remove('active'));$$('.nav-item').forEach(x=>x.classList.remove('active'));$(p).classList.add('active');document.querySelector(`.nav-item[data-page="${p}"]`)?.classList.add('active');$("pageTitle").textContent={dashboard:"Dashboard",collection:"Mijn binder",add:"Kaart toevoegen",scanner:"Foto scannen"}[p]||"The Vault";if(p==='dashboard')dash();if(p==='collection')binder()}
function dash(){let total=cards.reduce((s,c)=>s+c.quantity,0),op=cards.filter(c=>c.game==='One Piece TCG').reduce((s,c)=>s+c.quantity,0),mtg=total-op,val=cards.reduce((s,c)=>s+c.price*c.quantity,0);$("totalCards").textContent=total;$("uniqueCards").textContent=cards.length;$("opCount").textContent=op;$("mtgCount").textContent=mtg;$("foilCount").textContent=cards.filter(c=>c.foil).reduce((s,c)=>s+c.quantity,0);$("totalValue").textContent=euro.format(val);$("avgValue").textContent=euro.format(cards.length?val/cards.length:0);let a=total?Math.round(op/total*100):0,b=total?100-a:0;$("opPercent").textContent=a+'%';$("mtgPercent").textContent=b+'%';$("opBar").style.width=a+'%';$("mtgBar").style.width=b+'%';$("recentCards").innerHTML=cards.slice().sort((a,b)=>b.addedAt-a.addedAt).slice(0,4).map(c=>`<article class="recent-card"><div class="recent-card-image">${c.image?`<img src="${esc(c.image)}" alt="${esc(c.name)}">`:`<div class="preview-placeholder">${ini(c.name)}</div>`}</div><div class="recent-card-body"><h4>${esc(c.name)}</h4><p>${esc(c.game)} · ${esc(c.setName)} · x${c.quantity}</p><strong>${euro.format(c.quantity*c.price)}</strong></div></article>`).join('')||'<p class="muted">Nog geen kaarten in je collectie.</p>'}
function binder(){let q=$("searchInput").value.trim().toLowerCase(),g=$("gameFilter").value,s=$("sortFilter").value,a=cards.filter(c=>([c.name,c.setName,c.cardNumber,c.rarity].join(' ').toLowerCase().includes(q))&&(g==='all'||c.game===g));a.sort((x,y)=>s==='value'?y.price*y.quantity-x.price*x.quantity:s==='name'?x.name.localeCompare(y.name):y.addedAt-x.addedAt);$("resultCount").textContent=`${a.length} unieke kaarten`;$("emptyState").classList.toggle('hidden',!!a.length);$("cardGrid").innerHTML=a.map(c=>`<article class="binder-card"><div class="card-frame">${c.image?`<img src="${esc(c.image)}" alt="${esc(c.name)}">`:`<div class="preview-placeholder">${ini(c.name)}</div>`}<div class="badge-row"><span class="game-chip ${c.game==='One Piece TCG'?'op':'mtg'}">${c.game==='One Piece TCG'?'ONE PIECE':'MAGIC'}</span><span class="badge">x${c.quantity}</span></div>${c.foil?'<span class="foil-chip" style="position:absolute;left:10px;bottom:10px">FOIL</span>':''}<div class="card-overlay"></div></div><div class="card-info"><h4>${esc(c.name)}</h4><p>${esc(c.setName)} · ${esc(c.cardNumber||'—')} · ${esc(c.rarity)}</p><div class="card-info-footer"><strong>${euro.format(c.price)}</strong><button class="delete-btn" data-del="${c.id}">Verwijder</button></div></div></article>`).join('');$$('[data-del]').forEach(b=>b.onclick=()=>{cards=cards.filter(c=>c.id!==b.dataset.del);save();dash();binder();toast('Kaart verwijderd.')})}
function preview(){let n=$("name").value.trim()||'Nieuwe kaart',img=$("image").value.trim();$("previewGame").textContent=$("game").value;$("previewName").textContent=n;$("previewSet").textContent=$("setName").value.trim()||'Set';$("previewNumber").textContent=$("cardNumber").value.trim()||'000';$("previewImageWrap").innerHTML=img?`<img src="${esc(img)}" alt="${esc(n)}">`:`<div class="preview-placeholder">${ini(n)}</div>`}
const readFile=f=>new Promise((r,j)=>{let x=new FileReader;x.onload=()=>r(x.result);x.onerror=j;x.readAsDataURL(f)});
function add(c){cards.unshift(norm({...c,id:crypto.randomUUID(),addedAt:Date.now()}));save();dash();binder()}
function fill(c){$("game").value=c.game;$("name").value=c.name;$("setName").value=c.setName;$("cardNumber").value=c.cardNumber;$("rarity").value=c.rarity||'Rare';$("condition").value='Near Mint';$("quantity").value=1;$("price").value=c.price||0;$("foil").checked=!!c.foil;$("image").value=c.image||'';preview();nav('add');toast('Kaartdata ingevuld.')}
async function magic(q){let r=await fetch(`https://api.scryfall.com/cards/named?fuzzy=${encodeURIComponent(q)}`),d=await r.json();if(!r.ok||d.object==='error')return[];let image=d.image_uris?.normal||d.card_faces?.find(x=>x.image_uris)?.image_uris?.normal||'';return[{game:'Magic: The Gathering',name:d.name,setName:d.set_name||d.set?.toUpperCase()||'',cardNumber:d.collector_number||'',rarity:(d.rarity||'rare').replace(/\b\w/g,x=>x.toUpperCase()),condition:'Near Mint',quantity:1,price:+(d.prices?.eur||d.prices?.usd||d.prices?.usd_foil||0),foil:false,image}]}
const opCode=q=>{let m=q.toUpperCase().replace(/\s+/g,'').replace(/_/g,'-').match(/(OP|ST|P|EB|PRB|PR)0?\d{1,2}-\d{3}/);return m?m[0]:''};
const pick=(o,ks)=>{for(let k of ks)if(o?.[k]!=null&&o[k]!=='')return o[k];return''};
function oneNorm(raw,code){let d=Array.isArray(raw)?raw[0]:(raw.card||raw.data||raw);if(!d||typeof d!=='object')return null;let img=pick(d,['image','image_url','img','img_url','card_image','cardImage','photo_url']);if(!img){let st=[d];while(st.length&&!img){let o=st.pop();for(let[k,v]of Object.entries(o||{})){if(typeof v==='string'&&/(image|img|photo)/i.test(k)&&/^https?:/.test(v)){img=v;break}if(v&&typeof v==='object')st.push(v)}}}return{game:'One Piece TCG',name:pick(d,['name','card_name','cardName','english_name','title'])||code,setName:pick(d,['set_name','setName','set','set_id','deck_name'])||code.split('-')[0],cardNumber:pick(d,['card_id','cardId','id','code','number'])||code,rarity:String(pick(d,['rarity','card_rarity'])||'Rare').replace(/\b\w/g,x=>x.toUpperCase()),condition:'Near Mint',quantity:1,price:+(pick(d,['market_price','price','low_price','average_price'])||0),foil:false,image:img||''}}
async function one(code){for(let u of [`https://optcgapi.com/api/sets/card/${code}/`,`https://optcgapi.com/api/decks/card/${code}/`,`https://optcgapi.com/api/promos/card/${code}/`])try{let r=await fetch(u);if(r.ok){let c=oneNorm(await r.json(),code);if(c)return c}}catch{}return null}
async function lookup(){let q=$("lookupQuery").value.trim(),g=$("lookupGame").value,s=$("lookupStatus"),o=$("lookupResults");if(!q)return s.textContent='Voer eerst een zoekterm in.';s.textContent='Zoeken...';o.innerHTML='';let a=g==='Magic: The Gathering'?await magic(q):[(await one(opCode(q)))].filter(Boolean);s.textContent=a.length?`${a.length} resultaat gevonden.`:'Geen kaart gevonden.';o.innerHTML=a.map((c,i)=>`<article class="lookup-result"><div class="lookup-result-thumb">${c.image?`<img src="${esc(c.image)}">`:`<div class="preview-placeholder">${ini(c.name)}</div>`}</div><div><h4>${esc(c.name)}</h4><p>${esc(c.setName)} · ${esc(c.cardNumber||'—')}</p></div><button class="primary-btn" data-use="${i}">Gebruik</button></article>`).join('');$$('[data-use]').forEach(b=>b.onclick=()=>fill(a[+b.dataset.use]))}
async function hydrate(){let t=cards.filter(c=>!c.image).slice(0,12);if(!t.length)return toast('Alle kaarten hebben al een afbeelding.');$("hydrateImagesBtn").disabled=true;for(let c of t)try{let f=c.game==='Magic: The Gathering'?(await magic(c.name))[0]:await one(opCode(c.cardNumber));if(f?.image)c.image=f.image}catch{}save();binder();dash();$("hydrateImagesBtn").disabled=false;toast('Afbeeldingen bijgewerkt.')}
function clean(t){return String(t||'').replace(/[|\\]/g,'I').replace(/[^A-Za-z0-9À-ÿ'’.,:\- ]/g,' ').replace(/\s+/g,' ').trim().replace(/^[-:., ]+|[-:., ]+$/g,'')}
function sim(a,b){a=a.toLowerCase().replace(/[^a-z0-9]/g,'');b=b.toLowerCase().replace(/[^a-z0-9]/g,'');if(!a||!b)return 0;if(a===b||a.includes(b)||b.includes(a))return 1;let d=Array.from({length:a.length+1},(_,i)=>[i]);for(let j=1;j<=b.length;j++)d[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return 1-d[a.length][b.length]/Math.max(a.length,b.length)}
function loadImg(f){return new Promise((r,j)=>{let u=URL.createObjectURL(f),i=new Image;i.onload=()=>{URL.revokeObjectURL(u);r(i)};i.onerror=j;i.src=u})}
function enhance(c,strong){let x=c.getContext('2d',{willReadFrequently:true}),z=x.getImageData(0,0,c.width,c.height),d=z.data,k=strong?1.75:1.35,th=strong?165:null;for(let i=0;i<d.length;i+=4){let g=.299*d[i]+.587*d[i+1]+.114*d[i+2],v=Math.max(0,Math.min(255,(g-128)*k+128));if(th!==null)v=v>th?255:0;d[i]=d[i+1]=d[i+2]=v}x.putImageData(z,0,0)}
async function variants(f){let i=await loadImg(f),sc=Math.max(1,Math.min(3,1800/i.naturalWidth)),w=Math.round(i.naturalWidth*sc),h=Math.round(i.naturalHeight*sc),full=document.createElement('canvas');full.width=w;full.height=h;full.getContext('2d').drawImage(i,0,0,w,h);enhance(full,false);let title=document.createElement('canvas');title.width=w;title.height=Math.max(120,Math.round(h*.22));title.getContext('2d').drawImage(i,0,0,i.naturalWidth,Math.round(i.naturalHeight*.22),0,0,w,title.height);enhance(title,true);return{full,title}}
async function detect(text,title=''){let out=[],seen=new Set,up=text.toUpperCase().replace(/\s+/g,' '),codes=[...new Set((up.match(/(?:OP|ST|P|EB|PRB|PR)\s?0?\d{1,2}\s?[-–]\s?\d{3}/g)||[]).map(opCode))];for(let code of codes){let c=await one(code);if(c){out.push(c);seen.add(code)}}let lines=[title,...text.split(/\n+/)].map(clean).filter(x=>x.length>=3&&x.length<=45&&/[A-Za-z]/.test(x));for(let raw of [...new Set(lines)]){let q=raw.replace(/^\d+\s+/,'').replace(/\b(CREATURE|SORCERY|INSTANT|ARTIFACT|ENCHANTMENT|LAND|PLANESWALKER)\b.*$/i,'').replace(/\s+\d+\s*\/\s*\d+.*$/,'').trim();if(q.length<3)continue;try{let c=(await magic(q))[0];if(c&&sim(q,c.name)>=.7&&!seen.has(c.name.toLowerCase())){out.push(c);seen.add(c.name.toLowerCase());if(title&&sim(title,c.name)>=.7)break}}catch{}if(out.length>=8)break}return out.slice(0,8)}
function scanRender(a){$("scanResults").innerHTML=a.map((c,i)=>`<article class="scan-result-card"><div class="scan-result-thumb">${c.image?`<img src="${esc(c.image)}">`:`<div class="preview-placeholder">${ini(c.name)}</div>`}</div><div><h4>${esc(c.name)}</h4><p>${esc(c.game)} · ${esc(c.setName)} · ${esc(c.cardNumber||'—')}</p></div><div class="action-row"><button class="primary-btn" data-sfill="${i}">In formulier zetten</button><button class="ghost-btn" data-sadd="${i}">Direct toevoegen</button></div></article>`).join('');$$('[data-sfill]').forEach(b=>b.onclick=()=>fill(a[+b.dataset.sfill]));$$('[data-sadd]').forEach(b=>b.onclick=()=>{add(a[+b.dataset.sadd]);toast('Kaart toegevoegd.')})}
async function scan(){if(!scanFile)return $("scanStatus").textContent='Upload eerst een foto.';$("scanResults").innerHTML='';$("scanStatus").textContent='Kaartnaam bovenaan lezen...';let w;try{let v=await variants(scanFile);w=await Tesseract.createWorker('eng');await w.setParameters({tessedit_pageseg_mode:'7',preserve_interword_spaces:'1'});let tr=await w.recognize(v.title),title=clean(tr.data.text);await w.setParameters({tessedit_pageseg_mode:'6',preserve_interword_spaces:'1'});$("scanStatus").textContent='Extra kaartgegevens lezen...';let fr=await w.recognize(v.full),txt=(fr.data.text||'').trim(),all=[title,txt].filter(Boolean).join('\n');$("ocrText").textContent=all||'Geen tekst gevonden.';$("scanStatus").textContent='Kaartdatabase controleren...';let a=await detect(all,title);if(!a.length)return $("scanStatus").textContent=title?`Ik las “${title}”, maar vond geen zekere match.`:'Geen duidelijke kaartnaam herkend.';scanRender(a);$("scanStatus").textContent=`${a.length} kaartsuggestie${a.length===1?'':'s'} gevonden.`}catch(e){console.error(e);$("scanStatus").textContent='Scannen mislukt. Probeer de foto iets rechter of scherper.'}finally{if(w)await w.terminate()}}
$$('.nav-item').forEach(b=>b.onclick=()=>nav(b.dataset.page));$$('[data-goto]').forEach(b=>b.onclick=()=>nav(b.dataset.goto));$("quickAddBtn").onclick=()=>nav('add');$("openScannerBtn").onclick=()=>nav('scanner');$("lookupBtn").onclick=lookup;$("hydrateImagesBtn").onclick=hydrate;['searchInput','gameFilter','sortFilter'].forEach(id=>$(id).oninput=binder);['game','name','setName','cardNumber','image'].forEach(id=>$(id).oninput=preview);$("imageUpload").onchange=async e=>{let f=e.target.files?.[0];if(f){$("image").value=await readFile(f);preview()}};$("resetFormBtn").onclick=()=>{$("cardForm").reset();$("quantity").value=1;$("price").value=0;preview()};$("cardForm").onsubmit=e=>{e.preventDefault();add({game:$("game").value,name:$("name").value.trim(),setName:$("setName").value.trim(),cardNumber:$("cardNumber").value.trim(),rarity:$("rarity").value,condition:$("condition").value,quantity:Math.max(1,+$("quantity").value||1),price:Math.max(0,+$("price").value||0),foil:$("foil").checked,image:$("image").value.trim()});e.target.reset();$("quantity").value=1;$("price").value=0;preview();toast('Kaart toegevoegd aan je binder.');nav('collection')};$("scanImageInput").onchange=async e=>{scanFile=e.target.files?.[0]||null;if(scanFile){let u=await readFile(scanFile);$("scanPreview").classList.remove('hidden');$("scanPreview").innerHTML=`<img src="${u}">`;$("scanStatus").textContent='Foto geladen. Klaar om te scannen.'}};$("scanBtn").onclick=scan;$("clearScanBtn").onclick=()=>{scanFile=null;$("scanImageInput").value='';$("scanPreview").classList.add('hidden');$("scanPreview").innerHTML='';$("scanResults").innerHTML='';$("ocrText").textContent='Nog geen tekst gedetecteerd.';$("scanStatus").textContent='Nog geen scan gestart.'};preview();dash();binder();
