// The Vault Arena Hub — local-first match-history importer. No Arena credentials required.
(()=>{
  const STORE='vault-arena-history-v1', $=(s,r=document)=>r.querySelector(s), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  let state={matches:[],selectedDeck:'',inventory:{}};
  const load=()=>{try{state={...state,...JSON.parse(localStorage.getItem(STORE)||'{}')};if(!Array.isArray(state.matches))state.matches=[];if(!state.inventory||typeof state.inventory!=='object')state.inventory={}}catch{}};
  const save=()=>localStorage.setItem(STORE,JSON.stringify(state));
  const decks=()=>{try{return (JSON.parse(localStorage.getItem('vault-deck-lab-v1')||'{}').decks||[])}catch{return[]}};
  const today=()=>new Date().toISOString().slice(0,10);
  const norm=m=>({id:m.id||`arena-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,date:m.date||today(),deck:m.deck||'',format:m.format||'Constructed',result:['win','loss','draw'].includes(m.result)?m.result:'draw',opponent:m.opponent||'Onbekend',notes:m.notes||'',source:m.source||'manual'});
  function mount(){
    if($('#arena'))return;
    const nav=document.createElement('button');nav.className='nav-item';nav.dataset.page='arena';nav.innerHTML='<span class="nav-icon">◉</span><span class="nav-label">Arena</span>';
    $('.nav-list')?.appendChild(nav);nav.onclick=open;
    const page=document.createElement('section');page.id='arena';page.className='page';page.innerHTML=`
      <section class="arena-hero"><div><p class="small-label">MTG ARENA COMPANION</p><h2>Speel. Meet. <span>Verbeter.</span></h2><p>Synchroniseer lokaal wanneer jij wilt. Bekijk matchgeschiedenis, deckprestaties, formats en de accountgegevens die Arena in je log beschikbaar maakt.</p></div><div class="arena-privacy">⌁ <div><b>Privacy-first</b><small>Geen login · data blijft op dit apparaat</small></div></div></section>
      <div class="arena-layout"><section class="panel arena-import"><p class="small-label">1 · ARENA IMPORT</p><h3>Match history toevoegen</h3><p class="muted">Koppel één keer <b>Player.log</b>. Daarna leest Vault hem uitsluitend wanneer jij op <b>Sync Arena</b> drukt. Schakel in Arena eerst <i>Detailed Logs</i> in en herstart de game.</p><div class="arena-sync-actions"><button class="primary-btn" id="arenaLink">Koppel Arena-log</button><button class="ghost-btn" id="arenaSync" disabled>↻ Sync Arena</button></div><label class="arena-drop"><input id="arenaFile" type="file" accept=".log,.json,.txt"/><span>⌁</span><strong>Eenmalig importeren of backup kiezen</strong><small>Bestand en data blijven lokaal op dit apparaat</small></label><div class="arena-import-actions"><button class="ghost-btn" id="arenaDemo">Laad voorbeelddata</button><button class="text-btn" id="arenaExport">Exporteer backup</button></div><p id="arenaImportStatus" class="status-text muted">Nog geen Arena-log gekoppeld.</p></section>
      <section class="panel arena-insights"><div class="panel-header"><div><p class="small-label">2 · DECK PERFORMANCE</p><h3>Jouw Arena-overzicht</h3></div><button class="ghost-btn" id="arenaCoach">Maak coachplan</button></div><div id="arenaKpis" class="arena-kpis"></div><div id="arenaCoachText" class="arena-coach">Importeer matches of voeg er één handmatig toe. Daarna krijg je een concreet plan voor je volgende games.</div></section></div>
      <section class="arena-history-head"><div><div><p class="small-label">3 · HISTORY</p><h3>Recente matches</h3></div><button class="primary-btn" id="arenaAdd">+ Match toevoegen</button></div>
      <section class="panel arena-history"><div id="arenaDeckFilter" class="arena-filters"></div><div id="arenaRows" class="arena-rows"></div></section>
      <section class="arena-data-grid"><article class="panel arena-account"><div class="panel-header"><div><p class="small-label">4 · ARENA SNAPSHOT</p><h3>Account & collectie</h3></div></div><div id="arenaInventory" class="arena-inventory"></div><p class="arena-data-note">Gold, gems, packs, wildcards, Vault-progress en rank verschijnen alleen wanneer Arena ze in je Detailed Log schrijft.</p></article><article class="panel arena-breakdown"><div class="panel-header"><div><p class="small-label">5 · PERFORMANCE</p><h3>Decks & formats</h3></div></div><div id="arenaDeckStats" class="arena-stat-list"></div><div id="arenaFormatStats" class="arena-format-stats"></div></article></section>
      <dialog id="arenaDialog" class="arena-dialog"><form method="dialog" id="arenaForm"><div class="panel-header"><div><p class="small-label">MATCH LOG</p><h3>Match toevoegen</h3></div><button value="cancel" class="modal-close" aria-label="Sluiten">×</button></div><div class="arena-form-grid"><label>Datum<input name="date" type="date" value="${today()}" required></label><label>Resultaat<select name="result"><option value="win">Gewonnen</option><option value="loss">Verloren</option><option value="draw">Gelijkspel</option></select></label><label>Format<input name="format" placeholder="Standard, Historic…" value="Constructed"></label><label>Deck<select name="deck" id="arenaDeckSelect"></select></label><label>Opponent<input name="opponent" placeholder="Optioneel"></label><label class="wide">Notitie<input name="notes" placeholder="Bijv. mulligan naar 5, mana-screw, sterke sideboardkaart…"></label></div><div class="arena-dialog-actions"><button value="cancel" class="ghost-btn">Annuleren</button><button class="primary-btn" value="default">Match opslaan</button></div></form></dialog>`;
    $('main.content')?.appendChild(page);bind(page);render();
  }
  function bind(page){
    $('#arenaFile').onchange=e=>importFile(e.target.files?.[0],false);$('#arenaLink').onclick=linkLog;$('#arenaSync').onclick=syncLog;$('#arenaDemo').onclick=demo;$('#arenaExport').onclick=exportData;$('#arenaAdd').onclick=showDialog;$('#arenaCoach').onclick=coach;
    $('#arenaForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.matches.unshift(norm(Object.fromEntries(f)));save();$('#arenaDialog').close();render();coach()};
    page.addEventListener('click',e=>{const f=e.target.closest('[data-arena-filter]');if(f){state.selectedDeck=f.dataset.arenaFilter;render();return}const del=e.target.closest('[data-arena-delete]');if(del){state.matches=state.matches.filter(m=>m.id!==del.dataset.arenaDelete);save();render();}});
  }
  const pick=(text,keys)=>{for(const key of keys){const m=text.match(new RegExp(`(?:"${key}"|${key})["':=\\s]+(?:"?)([\\w .,-]+)`, 'i'));if(m)return m[1].trim()}return''};
  function snapshot(text){const money=v=>{const n=Number(String(v).replace(',','.'));return Number.isFinite(n)?n:undefined};return {gold:money(pick(text,['gold','Gold','goldAmount'])),gems:money(pick(text,['gems','Gems','gemAmount'])),packs:money(pick(text,['packs','Packs','packCount'])),commonWildcards:money(pick(text,['commonWildcards','wcCommon'])),uncommonWildcards:money(pick(text,['uncommonWildcards','wcUncommon'])),rareWildcards:money(pick(text,['rareWildcards','wcRare'])),mythicWildcards:money(pick(text,['mythicWildcards','wcMythic'])),vault:pick(text,['vaultProgress','VaultProgress']),rank:pick(text,['constructedRank','limitedRank','rank'])};}
  function parse(text,name){
    if(name.endsWith('.json')){const x=JSON.parse(text),list=(Array.isArray(x)?x:x.matches||[]).map(norm);return {matches:list,inventory:x.inventory||{}}}
    const chunks=text.split(/(?=matchId|MatchId|match_id)/i),out=[],seen=new Set();
    for(const c of chunks){const id=(c.match(/(?:matchId|MatchId|match_id)["':=\s]+([\w-]+)/i)||[])[1];if(!id||seen.has(id))continue;seen.add(id);const low=c.toLowerCase();const result=/\b(win|won|victory)\b/.test(low)?'win':/\b(loss|lost|defeat)\b/.test(low)?'loss':'draw';const fmt=(c.match(/(?:eventName|format)["':=\s]+([\w -]{3,40})/i)||[])[1]?.trim()||'Arena';const opponent=(c.match(/(?:opponent|opponentname)["':=\s]+([\w -]{3,40})/i)||[])[1]?.trim()||'Onbekend';const deck=(c.match(/(?:deckName|deckname)["':=\s]+([\w -]{2,60})/i)||[])[1]?.trim()||'';out.push(norm({id:`arena-${id}`,result,format:fmt,opponent,deck,source:'arena-log'}));}
    return {matches:out,inventory:snapshot(text)};
  }
  const fileDb=()=>new Promise((resolve,reject)=>{const r=indexedDB.open('vault-arena-file-v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('handles');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
  async function putHandle(h){const db=await fileDb();return new Promise((resolve,reject)=>{const t=db.transaction('handles','readwrite');t.objectStore('handles').put(h,'player-log');t.oncomplete=resolve;t.onerror=()=>reject(t.error)})}
  async function getHandle(){const db=await fileDb();return new Promise((resolve,reject)=>{const r=db.transaction('handles').objectStore('handles').get('player-log');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
  function syncUi(){const linked=!!state.linkedName;$('#arenaSync').disabled=!linked;if(linked&&!$('#arenaImportStatus').textContent.includes('geïmporteerd'))$('#arenaImportStatus').textContent=`Gekoppeld: ${state.linkedName}. Vault leest dit alleen als jij sync indrukt.`}
  async function linkLog(){try{if(!window.showOpenFilePicker){$('#arenaFile').click();return}const [handle]=await showOpenFilePicker({multiple:false,types:[{description:'MTG Arena log',accept:{'text/plain':['.log','.txt','.json']}}]});await putHandle(handle);state.linkedName=handle.name;save();syncUi();$('#arenaImportStatus').textContent=`${handle.name} gekoppeld. Druk op Sync Arena wanneer jij wilt ophalen.`}catch(err){if(err.name!=='AbortError')console.warn(err)}}
  async function syncLog(){try{const handle=await getHandle();if(!handle)throw Error('Geen gekoppeld log');const permission=await handle.queryPermission({mode:'read'});if(permission!=='granted'&&await handle.requestPermission({mode:'read'})!=='granted')throw Error('Toegang geweigerd');await importFile(await handle.getFile(),true)}catch(err){$('#arenaImportStatus').textContent='Koppel Player.log opnieuw om te syncen.';console.warn(err)}}
  async function importFile(file,linked=false){if(!file)return;try{const parsed=parse(await file.text(),file.name),items=parsed.matches||[],inventory=Object.fromEntries(Object.entries(parsed.inventory||{}).filter(([,v])=>v!==undefined&&v!==''));if(!items.length&&!Object.keys(inventory).length)throw Error('Geen Arena-data gevonden');const ids=new Set(state.matches.map(x=>x.id));const fresh=items.filter(x=>!ids.has(x.id));state.matches=[...fresh,...state.matches];state.inventory={...state.inventory,...inventory};state.lastSync=new Date().toISOString();if(linked)state.linkedName=file.name;save();render();syncUi();$('#arenaImportStatus').textContent=`${fresh.length} nieuwe match${fresh.length===1?'':'es'} geïmporteerd uit ${file.name}.`;coach()}catch(err){$('#arenaImportStatus').textContent='Import lukte niet. Gebruik Player.log met Detailed Logs aan, of voeg matches handmatig toe.';console.warn(err)}}
  function demo(){state.matches=[norm({id:'demo-1',date:today(),deck:decks()[0]?.name||'Mono Red Aggro',format:'Standard',result:'win',opponent:'Jace',notes:'Snelle pressure hield control klein.',source:'demo'}),norm({id:'demo-2',date:today(),deck:decks()[0]?.name||'Mono Red Aggro',format:'Standard',result:'loss',opponent:'Liliana',notes:'Te weinig land na mulligan.',source:'demo'}),norm({id:'demo-3',date:today(),deck:decks()[0]?.name||'Mono Red Aggro',format:'Standard',result:'win',opponent:'Kaya',notes:'Removal bewaard voor de finisher.',source:'demo'}),...state.matches.filter(m=>!m.id.startsWith('demo-'))];save();render();coach()}
  const record=items=>{const w=items.filter(m=>m.result==='win').length,l=items.filter(m=>m.result==='loss').length,total=items.length;return {w,l,total,rate:total?Math.round(w/total*100):0}};
  function renderData(all){const inv=state.inventory||{},value=(label,key)=>`<div><span>${label}</span><strong>${inv[key]??'—'}</strong></div>`;$('#arenaInventory').innerHTML=`${value('Gold','gold')}${value('Gems','gems')}${value('Packs','packs')}${value('Common WC','commonWildcards')}${value('Uncommon WC','uncommonWildcards')}${value('Rare WC','rareWildcards')}${value('Mythic WC','mythicWildcards')}${value('Vault','vault')}${value('Rank','rank')}`;const byDeck=[...new Set(all.map(m=>m.deck).filter(Boolean))].map(name=>[name,record(all.filter(m=>m.deck===name))]).sort((a,b)=>b[1].total-a[1].total);$('#arenaDeckStats').innerHTML=byDeck.length?byDeck.map(([name,r])=>`<div class="arena-stat-row"><strong>${esc(name)}</strong><span>${r.w}–${r.l} · ${r.rate}% over ${r.total}</span></div>`).join(''):'<p class="muted">Decknamen worden getoond zodra Arena ze in een match schrijft, of wanneer je ze handmatig koppelt.</p>';const byFormat=[...new Set(all.map(m=>m.format).filter(Boolean))].map(name=>[name,record(all.filter(m=>m.format===name))]);$('#arenaFormatStats').innerHTML=byFormat.map(([name,r])=>`<span>${esc(name)} <b>${r.rate}%</b></span>`).join('')||'<span>Nog geen formatdata</span>'}
  function render(){if(!$('#arenaRows'))return;const all=state.matches,shown=state.selectedDeck?all.filter(m=>m.deck===state.selectedDeck):all,{w,l,total,rate}=record(shown);$('#arenaKpis').innerHTML=`<article><span>MATCHES</span><strong>${total}</strong></article><article><span>WINRATE</span><strong>${total?rate+'%':'—'}</strong></article><article><span>RECORD</span><strong>${w}–${l}</strong></article>`;const names=[...new Set(all.map(m=>m.deck).filter(Boolean))];$('#arenaDeckFilter').innerHTML=`<button class="${!state.selectedDeck?'active':''}" data-arena-filter="">Alle decks <b>${all.length}</b></button>${names.map(n=>`<button class="${state.selectedDeck===n?'active':''}" data-arena-filter="${esc(n)}">${esc(n)} <b>${all.filter(m=>m.deck===n).length}</b></button>`).join('')}`;$('#arenaRows').innerHTML=shown.map(m=>`<article class="arena-row"><span class="arena-result ${m.result}">${m.result==='win'?'W':m.result==='loss'?'V':'G'}</span><div><strong>${esc(m.deck||'Niet gekoppeld')}</strong><small>${esc(m.format)} · vs ${esc(m.opponent)} · ${esc(m.date)}</small>${m.notes?`<em>${esc(m.notes)}</em>`:''}</div><button class="text-btn" data-arena-delete="${esc(m.id)}" aria-label="Verwijder match">×</button></article>`).join('')||'<div class="arena-empty">Nog geen matches. Importeer je Arena-log of voeg de eerste match toe.</div>';renderData(all)}
  function showDialog(){const sel=$('#arenaDeckSelect');sel.innerHTML='<option value="">Niet gekoppeld</option>'+decks().map(d=>`<option value="${esc(d.name)}">${esc(d.name)} · ${esc(d.format)}</option>`).join('');$('#arenaDialog').showModal()}
  function coach(){const shown=state.selectedDeck?state.matches.filter(m=>m.deck===state.selectedDeck):state.matches,w=shown.filter(m=>m.result==='win').length,losses=shown.filter(m=>m.result==='loss'),rate=shown.length?Math.round(w/shown.length*100):0;let text=!shown.length?'Voeg eerst een paar matches toe. Noteer bij verlies kort waarom: mulligan, mana, tempo of een specifieke kaart.' : `<b>${rate}% winrate</b> over ${shown.length} matches. `;if(shown.length){if(rate<50)text+='Focus komende games op een eenvoudig, herhaalbaar spelplan: houd handen met mana én een actie voor beurt 2–3, en noteer elke mulligan.';else text+='Je basis werkt. Test nu één bewuste aanpassing tegelijk en vergelijk je volgende vijf matches.';if(losses.some(m=>/mulligan|mana/i.test(m.notes)))text+=' Je notities wijzen op mana/mulligan-problemen: evalueer je landaantal en houd minder grensgevallen.';text+=' Bewaar removal voor kaarten die jouw win condition blokkeren, niet alleen voor de eerste dreiging.'}$('#arenaCoachText').innerHTML=text}
  function exportData(){const blob=new Blob([JSON.stringify({matches:state.matches},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='vault-arena-history.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  function open(){if(typeof nav==='function')nav('arena');render();syncUi()}
  load();mount();syncUi();
})();
